title: "Mamadou Abdoulaye Diallo"
logo: assets/images/photo.jpg
description: ""
show_downloads: false
url: "https://300786147.github.io"
baseurl: "/mamadou.diallo"

theme: jekyll-theme-minimal

author:
  name: "Mamadou Abdoulaye Diallo"
  email: "mamadouabdoulayediallo52@gmail.com"
  location: "Toronto, ON"
  github: "300786147"

markdown: kramdown
highlighter: rouge
encoding: utf-8
lang: fr

github:
  is_project_page: false
